### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by lumix1991** [w3c/css-validator#8]
Dear,

How can I install this validator on my CentOS machine?

I tried to build it manually but can't resolve the following java error;

HTTP Status 500 - Servlet execution threw an exception
type Exception report
message Servlet execution threw an exception
description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Servlet execution threw an exception
root cause

java.lang.NoClassDefFoundError: Could not initialize class org.w3c.css.css.StyleSheetGenerator
org.w3c.css.css.StyleReportFactory.getStyleReport(StyleReportFactory.java:18)
org.w3c.css.servlet.CssValidator.handleRequest(CssValidator.java:730)
org.w3c.css.servlet.CssValidator.doGet(CssValidator.java:371)
javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.33 logs.

Apache Tomcat/7.0.33

**Comment by jaimeiniesta** [comment]
@lumix1991 the build instructions you refer to are outdated; there's an executable file `sbt` in this repo that launches the build.

**Comment by jaimeiniesta** [comment]
Said that, I don't know what the dependencies are (openjdk-7-jdk maybe?), how the `sbt` command should be run (does it need more arguments) and what to do with it.

Can you please add a bit of documentation about how to install the CSS validator?

Thanks!

**Comment by cvrebert** [comment]
@betehess Any chance you could enlighten us?

**Comment by betehess** [comment]
`sbt` itself should work with any Java >= 1.7. The version being used is quite [old](https://github.com/w3c/css-validator/blob/master/project/build.properties) and I know that some repositories got moved around in the past 2 years, so it might not resolve...

**Comment by cvrebert** [comment]
See https://github.com/w3c/css-validator/issues/6
